site_description: "Vue.js - The Progressive JavaScript Framework"
google_analytics: UA-46852172-1
root_domain: vuejs.org
vue_version: 2.5.16

special_sponsors:
  - url: https://stdlib.com
    img: stdlib.png

platinum_sponsors:
  - url: https://www.bitsrc.io/?utm_source=vue&utm_medium=vue&utm_campaign=vue&utm_term=vue&utm_content=vue
    img: bit-wide.png
    alt_img: bit.png
  - url: http://tooltwist.com/
    img: tooltwist.png
  - url: https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
  - url: https://vehikl.com/
    img: vehikl.png

gold_sponsors:
  - url: https://laravel.com
    img: laravel.png
  - url: https://htmlburger.com
    img: htmlburger.png
  - url: https://chaitin.cn/en/
    img: chaitin.png
  - url: https://www.frontenddeveloperlove.com/
    img: frontend-love.png
  - url: https://onsen.io/vue/
    img: onsen-ui.png
  - url: https://vuetifyjs.com
    img: vuetify.png
  - url: https://neds.com.au/
    img: neds.png
  - url: https://hackr.io/tutorials/learn-vue-js
    img: hackr-io.png
  - url: https://icons8.com/
    img: icons8.png
  - url: https://vuejobs.com/?ref=vuejs
    img: vuejobs.png
  - url: https://codepilot.ai
    img: codepilot.png
  - url: https://teamextension.io/
    img: teamextension.png
  - url: http://aaha.co/
    img: aaha.png
  - url: https://www.valuecoders.com
    img: valuecoders.png
  - url: https://www.nsoft.com/careers/
    img: nsoft.png
  - url: https://www.vuemastery.com/
    img: vuemastery.png

silver_sponsors:
  - url: https://dopamine.bg/
    img: dopamine.png

bronze_sponsors:
  - url: http://tighten.co/
    img: http://i.imgur.com/T7fQYLT.png
  - url: https://alligator.io
    img: https://alligator.io/images/alligator-logo.svg
  - url: https://www.accelebrate.com/
    img: https://www.accelebrate.com/assets/images/accelebrate_logo@2x.png
  - url: https://pullstring.com
    img: https://i.imgur.com/hQHW6TB.png
