site_description: Vue.js - The Progressive JavaScript Framework
google_analytics: UA-46852172-1
root_domain: vuejs.org
vue_version: 2.5.16
platinum_sponsors_china:
  - url: 'http://www.dcloud.io/?hmsr=vuejsorg&hmpl=&hmcu=&hmkw=&hmci='
    img: dcloud.gif
special_sponsors:
  - url: 'https://stdlib.com/'
    img: stdlib.png
    description: 'Build APIs you need in minutes instead of days, for free.'
platinum_sponsors:
  - url: >-
      https://bit.dev/?utm_source=vue&utm_medium=vue&utm_campaign=vue&utm_term=vue&utm_content=vue
    img: bit.png
    name: Bit
  - url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
    name: VueSchool
  - url: 'https://vehikl.com/'
    img: vehikl.png
    name: Vehikl
  - url: >-
      https://www.nativescript.org/vue?utm_source=vue-js-org&utm_medium=website&utm_campaign=nativescript-awareness
    img: nativescript.png
    name: NativeScript
gold_sponsors:
  - url: 'https://www.vuemastery.com/'
    img: vuemastery.png
    name: VueMastery
  - url: 'https://laravel.com'
    img: laravel.png
    name: Laravel
  - url: 'https://chaitin.cn/en/'
    img: chaitin.png
    name: Chaitin
  - url: 'https://htmlburger.com'
    img: html_burger.png
    name: HTML Burger
  - url: 'https://www.frontenddeveloperlove.com/'
    img: frontendlove.png
    name: FrontendLove
  - url: 'https://onsen.io/vue/'
    img: onsen_ui.png
    name: Onsen UI
  - url: 'https://neds.com.au/'
    img: neds.png
    name: Neds
  - url: 'https://icons8.com/'
    img: icons_8.png
    name: Icons 8
  - url: 'https://vuejobs.com/?ref=vuejs'
    img: vuejobs.png
    name: VueJobs
  - url: 'https://tidelift.com/subscription/npm/vue'
    img: tidelift.png
    name: Tidelift
  - url: 'https://opteo.com/vue'
    img: opteo.png
    name: Opteo
  - url: 'https://devsquad.com/'
    img: devsquad.png
    name: DevSquad
  - url: 'https://www.firesticktricks.com/'
    img: firestick_tricks.png
    name: Firestick Tricks
  - url: 'https://intygrate.com/'
    img: intygrate.png
    name: Intygrate
  - url: 'https://passionatepeople.io/'
    img: passionate_people.png
    name: Passionate People
  - url: 'http://en.shopware.com/'
    img: shopware_ag.png
    name: shopware AG
  - url: 'https://www.vpnranks.com/'
    img: vpnranks.png
    name: VPNRanks
  - url: 'https://www.simplyswitch.com/'
    img: energy_comparison.png
    name: Energy Comparison
  - url: 'https://www.bacancytechnology.com'
    img: bacancy_technology.png
    name: Bacancy Technology
  - url: 'https://www.bestvpn.co/'
    img: bestvpn_co.png
    name: BestVPN.co
  - url: 'https://blokt.com/'
    img: blokt_cryptocurrency_news.png
    name: Blokt Cryptocurrency News
  - url: 'https://www.y8.com/'
    img: y8.png
    name: Y8
  - url: 'https://js.devexpress.com/'
    img: devexpress.png
    name: DevExpress
  - url: 'https://fastcoding.jp/javascript/ '
    img: fastcoding_inc.svg
    name: FASTCODING Inc
  - url: 'https://usave.co.uk/utilities/broadband'
    img: usave.png
    name: usave
  - url: 'https://www.dailynow.co/'
    img: daily.png
    name: Daily
  - url: 'https://storekit.com'
    img: storekit.png
    name: StoreKit
silver_sponsors:
  - url: 'https://dopamine.bg/'
    img: dopamine.png
    name: Dopamine
bronze_sponsors:
  - url: 'https://www.accelebrate.com/'
    img: accelebrate.png
    name: Accelebrate
  - url: 'https://polyglotengineer.com/derek.pollard'
    img: derek_pollard.png
    name: Derek Pollard
  - url: 'https://www.earthlink.ro'
    img: earthlink.png
    name: Earthlink
