site_description: Vue.js - The Progressive JavaScript Framework
google_analytics: UA-46852172-1
root_domain: vuejs.org
vue_version: 2.5.16
platinum_sponsors_china:
  - url: 'http://www.dcloud.io/?hmsr=vuejsorg&hmpl=&hmcu=&hmkw=&hmci='
    img: dcloud.gif
special_sponsors:
  - url: 'https://stdlib.com/'
    img: stdlib.png
    name: Standard Library
    description: 'Build APIs you need in minutes instead of days, for free.'
platinum_sponsors:
  - url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
    name: VueSchool
  - url: 'https://vehikl.com/'
    img: vehikl.png
    name: Vehikl
  - url: 'https://retool.com/?utm_source=sponsor&utm_campaign=vue'
    img: retool.png
    name: Retool
  - url: 'https://passionatepeople.io/'
    img: passionate_people.png
    name: Passionate People
gold_sponsors:
  - url: 'https://www.vuemastery.com/'
    img: vuemastery.png
    name: VueMastery
  - url: 'https://laravel.com'
    img: laravel.png
    name: Laravel
  - url: 'https://htmlburger.com'
    img: html_burger.png
    name: HTML Burger
  - url: 'https://www.frontenddeveloperlove.com/'
    img: frontendlove.png
    name: FrontendLove
  - url: 'https://onsen.io/vue/'
    img: onsen_ui.png
    name: Onsen UI
  - url: 'https://neds.com.au/'
    img: neds.png
    name: Neds
  - url: 'https://icons8.com/'
    img: icons_8.png
    name: Icons 8
  - url: 'https://vuejobs.com/?ref=vuejs'
    img: vuejobs.png
    name: VueJobs
  - url: 'https://tidelift.com/subscription/npm/vue'
    img: tidelift.png
    name: Tidelift
  - url: 'https://opteo.com/vue'
    img: opteo.png
    name: Opteo
  - url: 'https://devsquad.com/'
    img: devsquad.png
    name: DevSquad
  - url: 'https://www.firesticktricks.com/'
    img: firestick_tricks.png
    name: Firestick Tricks
  - url: 'https://intygrate.com/'
    img: intygrate.png
    name: Intygrate
  - url: 'http://en.shopware.com/'
    img: shopware_ag.png
    name: shopware AG
  - url: 'https://www.simplyswitch.com/'
    img: energy_comparison.png
    name: Energy Comparison
  - url: 'https://www.bacancytechnology.com'
    img: bacancy_technology.png
    name: Bacancy Technology
  - url: 'https://www.y8.com/'
    img: y8.png
    name: Y8
  - url: 'https://js.devexpress.com/'
    img: devexpress.png
    name: DevExpress
  - url: 'https://fastcoding.jp/javascript/ '
    img: fastcoding_inc.svg
    name: FASTCODING Inc
  - url: 'https://usave.co.uk/utilities/broadband'
    img: usave.png
    name: usave
  - url: 'https://www.dailynow.co/'
    img: daily.png
    name: Daily
  - url: 'https://storekit.com'
    img: storekit.png
    name: StoreKit
  - url: 'http://www.pullrequest.com'
    img: pullrequest.svg
    name: PullRequest
  - url: 'https://unicorn.io/'
    img: unicorn_io.png
    name: Unicorn.io
  - url: 'https://www.programmers.io'
    img: programmers_io.png
    name: Programmers.io
  - url: 'https://www.primefaces.org/primevue'
    img: primevue.png
    name: PrimeVue
silver_sponsors:
  - url: 'https://roadster.com'
    img: roadster.png
    name: Roadster
  - url: 'https://www.inkoop.io'
    img: inkoop.png
    name: Inkoop
bronze_sponsors:
  - url: 'https://www.accelebrate.com/'
    img: accelebrate.png
    name: Accelebrate
  - url: 'https://polyglotengineer.com/derek.pollard'
    img: derek_pollard.png
    name: Derek Pollard
  - url: 'https://www.earthlink.ro'
    img: earthlink.png
    name: Earthlink
  - url: 'https://www.webucator.com'
    img: webucator.png
    name: Webucator
