site_description: Vue.js - The Progressive JavaScript Framework
google_analytics: UA-46852172-1
root_domain: vuejs.org
vue_version: 2.5.16
special_sponsors:
  - url: 'https://www.dcloud.io/hbuilderx.html?hmsr=vue-en&hmpl=&hmcu=&hmkw=&hmci='
    img: hbuilder.png
    name: HBuilder
    description: An IDE for Vue
platinum_sponsors_china:
  - url: 'https://www.dcloud.io/hbuilderx.html?hmsr=vue-en&hmpl=&hmcu=&hmkw=&hmci='
    img: hbuilder.png
    name: HBuilder
    description: An IDE for Vue
  - name: authing
    url: >-
      https://www.authing.cn/welcome?utm_source=Vuejs&utm_medium=CPT&utm_campaign=EN&utm_term=page-EN
    img: authing.svg
  - name: qingfuwu
    url: https://qingfuwu.cn?utm_campaign=TR_eSJH7nqW&utm_content=&utm_medium=Web&utm_source=CH_53OxwryD&utm_term=
    img: qingfuwu-v2.svg
platinum_sponsors:
  - url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
    name: VueSchool
  - url: 'https://vehikl.com/'
    img: vehikl.png
    name: Vehikl
  - url: 'https://passionatepeople.io/'
    img: passionate_people.png
    name: Passionate People
  - url: 'https://www.storyblok.com'
    img: storyblok.png
    name: Storyblok
  - url: >-
      https://ionicframework.com/vue?utm_source=partner&utm_medium=referral&utm_campaign=vuesponsorship&utm_content=vuedocs
    img: ionic.png
    name: Ionic
  - url: 'https://nuxtjs.org/'
    img: nuxt.png
    name: Nuxt
  - url: 'https://www.refurbed.org/?utm_source=vuejs'
    img: refurbed.png
    name: Refurbed
gold_sponsors:
  - url: 'https://www.vuemastery.com/'
    img: vuemastery.png
    name: VueMastery
  - url: 'https://laravel.com'
    img: laravel.png
    name: Laravel
  - url: 'https://htmlburger.com'
    img: html_burger.png
    name: HTML Burger
  - url: 'https://www.frontenddeveloperlove.com/'
    img: frontendlove.png
    name: FrontendLove
  - url: 'https://neds.com.au/'
    img: neds.png
    name: Neds
  - url: 'https://icons8.com/'
    img: icons_8.png
    name: Icons 8
  - url: 'https://tidelift.com/subscription/npm/vue'
    img: tidelift.png
    name: Tidelift
  - url: 'https://www.firesticktricks.com/'
    img: firestick_tricks.png
    name: Firestick Tricks
  - url: 'https://intygrate.com/'
    img: intygrate.png
    name: Intygrate
  - url: 'http://en.shopware.com/'
    img: shopware_ag.png
    name: shopware AG
  - url: 'https://www.vpnranks.com/'
    img: vpnranks.png
    name: VPNRanks
  - url: 'https://www.bacancytechnology.com/hire-vuejs-developer'
    img: bacancy_technology.png
    name: Bacancy Technology
  - url: 'https://www.bestvpn.co/'
    img: bestvpn_co.png
    name: BestVPN.co
  - url: 'https://www.y8.com/'
    img: y8.png
    name: Y8
  - url: 'https://js.devexpress.com/'
    img: devexpress.png
    name: DevExpress
  - url: 'https://fastcoding.jp/javascript/ '
    img: fastcoding_inc.svg
    name: FASTCODING Inc
  - url: 'https://usave.co.uk/utilities/broadband'
    img: usave.png
    name: usave
  - url: 'https://storekit.com'
    img: storekit.png
    name: StoreKit
  - url: 'https://www.foo.software'
    img: foo.png
    name: Foo
  - url: 'https://flatlogic.com/templates'
    img: flatlogic_templates.svg
    name: Flatlogic Templates
  - url: 'https://www.layer0.co'
    img: layer0.png
    name: Layer0
  - url: 'https://vpn-review.com/netflix-vpn'
    img: vpn_review.png
    name: VPN Review
  - url: 'https://cosmos.network/'
    img: tendermint.png
    name: Tendermint
  - url: 'https://www.okayhq.com/'
    img: okay.png
    name: Okay
  - url: 'https://www.vpsserver.com'
    img: vpsserver_com.png
    name: VPSServer.com
  - url: 'https://aussiecasinohex.com/'
    img: aussiecasinohex.svg
    name: AussieCasinoHEX
  - url: 'https://litslink.com'
    img: litslink.png
    name: LITSLINK
  - url: 'https://newicon.net'
    img: newicon.png
    name: Newicon
  - url: 'https://lowdefy.com?k=w432'
    img: lowdefy.png
    name: Lowdefy
  - url: 'https://quickbookstoolhub.com/'
    img: quickbooks_tool_hub.png
    name: Quickbooks Tool Hub
  - url: 'https://linecorp.com'
    img: line_corporation.png
    name: LINE Corporation
  - url: 'https://exmax.it/'
    img: exmax.png
    name: Exmax
  - url: 'https://plaid.co.jp/'
    img: plaid__inc_.svg
    name: 'PLAID, Inc.'
  - url: 'https://troypoint.com'
    img: troypoint.png
    name: TROYPOINT
  - url: >-
      https://webreinvent.com?utm_source=vuejs.org&utm_medium=logo&utm_campaign=patreon-sponsors
    img: webreinvent_technologies_pvt_ltd.svg
    name: WebReinvent Technologies Pvt Ltd
  - url: 'https://www.dronahq.com/?ref=github_Vuejs'
    img: dronahq.png
    name: DronaHQ
  - url: 'https://www.emqx.com'
    img: emq.png
    name: EMQ
  - url: >-
      https://www.tatvasoft.com/software-development-technology/vue-js-development-services
    img: tatvasoft.png
    name: TatvaSoft
  - url: 'https://www.aceonlinecasino.co.uk'
    img: onyx_gaming_limited.svg
    name: Onyx Gaming Limited
  - url: 'http://www.lendio.com'
    img: lendio.png
    name: Lendio
  - url: >-
      https://flowdash.com/?utm_source=vue&utm_medium=sponsor&utm_campaign=open-source
    img: flowdash.png
    name: Flowdash
  - url: 'https://www.fenetre.nl/english/'
    img: fen_tre_online_solutions.png
    name: FenÃªtre Online Solutions
  - url: 'https://finclip.com/?from=vue'
    img: finclip.png
    name: FinClip
silver_sponsors:
  - url: 'https://roadster.com'
    img: roadster.png
    name: Roadster
  - url: 'https://www.inkoop.io'
    img: inkoop.png
    name: Inkoop
  - url: 'https://www.thecasinodb.com'
    img: isolutions_uk_limited.png
    name: iSolutions UK Limited
  - url: 'https://teamextension.io'
    img: team_extension_north_america_inc.png
    name: Team Extension North America Inc
  - url: 'https://freebets.us'
    img: free_bets_us.png
    name: Free Bets US
  - url: 'https://betting.bet'
    img: betting_bet.png
    name: betting.bet
  - url: 'https://www.takt.io'
    img: takt.png
    name: Takt
  - url: 'https://technology.doximity.com/'
    img: doximity.png
    name: Doximity
  - url: 'https://www.empiricus.com.br/'
    img: empiricus.png
    name: Empiricus
bronze_sponsors:
  - url: 'https://www.accelebrate.com/'
    img: accelebrate.png
    name: Accelebrate
  - url: 'https://polyglotengineer.com/derek.pollard'
    img: derek_pollard.png
    name: Derek Pollard
  - url: 'https://www.earthlink.ro'
    img: earthlink.png
    name: Earthlink
  - url: 'https://www.webucator.com'
    img: webucator.png
    name: Webucator
  - url: 'https://memberful.com/'
    img: memberful.png
    name: Memberful
