# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: Vue.js
subtitle:
description: "The Progressive JavaScript Framework"
author: Evan You
email:
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://cn.vuejs.org
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: src
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: vue
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:vuejs/cn.vuejs.org.git
  branch: gh-pages

feed:
  type: atom
  path: atom.xml
  limit: 20

alias:
  api/index.html: v2/api/index.html
  guide/class-and-style.html: v2/guide/class-and-style.html
  guide/comparison.html: v2/guide/comparison.html
  guide/components.html: v2/guide/components.html
  guide/computed.html: v2/guide/computed.html
  guide/conditional.html: v2/guide/conditional.html
  guide/custom-directive.html: v2/guide/custom-directive.html
  guide/deployment.html: v2/guide/deployment.html
  guide/events.html: v2/guide/events.html
  guide/forms.html: v2/guide/forms.html
  guide/index.html: v2/guide/index.html
  guide/installation.html: v2/guide/installation.html
  guide/instance.html: v2/guide/instance.html
  guide/join.html: v2/guide/join.html
  guide/list.html: v2/guide/list.html
  guide/migration-vue-router.html: v2/guide/migration-vue-router.html
  guide/migration-vuex.html: v2/guide/migration-vuex.html
  guide/migration.html: v2/guide/migration.html
  guide/mixins.html: v2/guide/mixins.html
  guide/plugins.html: v2/guide/plugins.html
  guide/reactivity.html: v2/guide/reactivity.html
  guide/render-function.html: v2/guide/render-function.html
  guide/routing.html: v2/guide/routing.html
  guide/single-file-components.html: v2/guide/single-file-components.html
  guide/ssr.html: v2/guide/ssr.html
  guide/state-management.html: v2/guide/state-management.html
  guide/syntax.html: v2/guide/syntax.html
  guide/transitioning-state.html: v2/guide/transitioning-state.html
  guide/transitions.html: v2/guide/transitions.html
  guide/unit-testing.html: v2/guide/unit-testing.html
  examples/commits.html: v2/examples/commits.html
  examples/elastic-header.html: v2/examples/elastic-header.html
  examples/firebase.html: v2/examples/firebase.html
  examples/grid-component.html: v2/examples/grid-component.html
  examples/hackernews.html: v2/examples/hackernews.html
  examples/index.html: v2/examples/index.html
  examples/modal.html: v2/examples/modal.html
  examples/select2.html: v2/examples/select2.html
  examples/svg.html: v2/examples/svg.html
  examples/todomvc.html: v2/examples/todomvc.html
  examples/tree-view.html: v2/examples/tree-view.html

